#在github代码托管中心的https://github.com/hupeng2966/foyoedu-config.git里获取foyoedu-zuul-config微服务的配置文件
server:
  port: 9527

spring:
  application:
    name: foyoedu-zuul
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  security:
    user:
      name: foyoedu
      password: foyoedu

eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka.foyoedu.com:7001/eureka

zuul:
  #prefix: /foyoedu
  sensitive-headers: true
  ignored-services: "*"
  routes:
    FOYOEDU-PROVIDER-BASE: /base/**
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
      circuitBreaker:
        sleepWindowInMilliseconds: 60000
        forceClosed: true

ribbon:
  SocketTimeout: 60000
  ConnectTimeout: 60000
  ReadTimeout: 60000

info:
  app.name: foyoedu
  company.name: www.foyoedu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
