#在github代码托管中心的https://github.com/hupeng2966/foyoedu-config.git里获取foyoedu-zuul-config微服务的配置文件
server:
  port: 9527

spring:
  application:
    name: foyoedu-zuul

eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka.foyoedu.com:7001/eureka


zuul:
  #prefix: /foyoedu
  sensitive-headers: true
  ignored-services: "*"
  routes:
    FOYOEDU-PROVIDER-BASE: /base/**
  trace-request-body: true

security:
  basic:
    enabled: true
  user:
    name: foyoedu
    password: foyoedu

info:
  app.name: foyoedu
  company.name: www.foyoedu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
