#在github代码托管中心的https://github.com/hupeng2966/foyoedu-config.git里获取foyoedu-provider-base-config微服务的配置文件
#server:
#  port: 8001
#
#mybatis:
#  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
#  type-aliases-package: com.foyoedu.common.pojo    # 所有pojo别名类所在包
##  mapper-locations:
##  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
#
#spring:
#  application:
#    name: foyoedu-provider-base
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
#    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
#    url: jdbc:mysql://192.168.0.68:3306/foyoedu?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true             # 数据库名称useUnicode=true
#    username: root
#    password: foyoedu
#    dbcp2:
#      min-idle: 10                                           # 数据库连接池的最小维持连接数
#      initial-size: 10                                       # 初始化连接数
#      max-total: 100                                          # 最大连接数
#      max-wait-millis: 30000                                  # 等待连接获取的最大超时时间
#  http:
#    encoding:
#      charset: utf-8
#      enabled: true
#      force: true                                           #server.tomcat.uri-encoding=UTF-8
#
#eureka:
#  client: #客户端注册进eureka服务列表内
#    service-url:
#      defaultZone: http://eureka.foyoedu.com:7001/eureka/
#      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#  instance:
#    instance-id: ${spring.application.name}-${server.port}
#    prefer-ip-address: true     #访问路径可以显示IP地址
#

info:
  app.name: foyoedu
  company.name: www.foyoedu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}



