#在github代码托管中心的https://github.com/hupeng2966/foyoedu-config.git里获取foyoedu-provider-standart-config微服务的配置文件
#server:
#  port: 8002
#
#spring:
#  application:
#    name: foyoedu-provider-standart
#  http:
#    encoding:
#      charset: utf-8
#      enabled: true
#      force: true                                           #server.tomcat.uri-encoding=UTF-8
#
#eureka:
#  client: #客户端注册进eureka服务列表内
#    service-url:
#      defaultZone: http://eureka.foyoedu.com:7001/eureka/
#      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#  instance:
#    instance-id: ${spring.application.name}-${server.port}
#    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: foyoedu
  company.name: www.foyoedu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
