#在github代码托管中心的https://github.com/hupeng2966/foyoedu-config.git里获取foyoedu-provider-standart-config微服务的配置文件
server:
  port: 8002

spring:
  application:
    name: foyoedu-provider-standart

eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: foyoedu
  company.name: www.foyoedu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
