##在github代码托管中心的https://github.com/hupeng2966/foyoedu-config.git里获取foyoedu-consumer-config微服务的配置文件
#server:
#  port: 80
#
#eureka:
#  client:
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://eureka.foyoedu.com:7001/eureka/
#
#feign:
#  hystrix:
#    enabled: true
#
#spring:
#  http:
#    encoding:
#      enabled: true
#      charset: UTF-8
#      force: true
#
spring:
  redis:
    host: 192.168.0.68

cookie:
  token_key: token

login:
  uri: login/login.html
