##在github代码托管中心的https://github.com/hupeng2966/foyoedu-config.git里获取foyoedu-consumer-config微服务的配置文件
server:
  port: 80

eureka:
  client:
    register-with-eureka: false

feign:
  hystrix:
    enabled: true

login:
  uri: login/login.html

